### ISSUE TITLE
Docker is not working

### ISSUE THREAD

**Issue by rgaiacs** [codecheckers/codecheckers.github.io#9]
```
codecheckersgithubio-jekyll-1  | ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
codecheckersgithubio-jekyll-1  | /usr/gem/gems/kramdown-1.17.0/lib/kramdown/parser/html.rb:10:in `require': cannot load such file -- rexml/parsers/baseparser (LoadError)
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/kramdown-1.17.0/lib/kramdown/parser/html.rb:10:in `<top (required)>'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/html.rb:10:in `require'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/html.rb:10:in `<top (required)>'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/paragraph.rb:14:in `require'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown/paragraph.rb:14:in `<top (required)>'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:345:in `require'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:345:in `<class:Kramdown>'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:60:in `<module:Parser>'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:19:in `<module:Kramdown>'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/kramdown-1.17.0/lib/kramdown/parser/kramdown.rb:17:in `<top (required)>'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/jekyll-3.8.7/lib/jekyll/converters/smartypants.rb:3:in `require'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/jekyll-3.8.7/lib/jekyll/converters/smartypants.rb:3:in `<top (required)>'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/jekyll-3.8.7/lib/jekyll.rb:13:in `require'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/jekyll-3.8.7/lib/jekyll.rb:13:in `block in require_all'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/jekyll-3.8.7/lib/jekyll.rb:12:in `each'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/jekyll-3.8.7/lib/jekyll.rb:12:in `require_all'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/jekyll-3.8.7/lib/jekyll.rb:194:in `<top (required)>'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/jekyll-3.8.7/exe/jekyll:8:in `require'
codecheckersgithubio-jekyll-1  |        from /usr/gem/gems/jekyll-3.8.7/exe/jekyll:8:in `<top (required)>'
codecheckersgithubio-jekyll-1  |        from /usr/local/bundle/bin/jekyll:29:in `load'
codecheckersgithubio-jekyll-1  |        from /usr/local/bundle/bin/jekyll:29:in `<main>'
```

**Comment by rgaiacs** [comment]
Reported upstream at https://github.com/envygeeks/jekyll-docker/issues/340.

**Comment by nuest** [comment]
Should be fixed by now.
